# Consiguiendo los datos

### Conseguir el link

In [4]:
url = "https://import.cdn.thinkific.com/220744/courses/1648061/pokemon_dataset-220322-181028.zip"

### Descargar el archivo

In [5]:
import urllib.request as Req

In [9]:
Req.urlretrieve(url, "pokemon_dataset.zip")  #Aquí ponemos la ruta donde queremos que se aloje

('pokemon_dataset.zip', <http.client.HTTPMessage at 0x1c344ea8970>)

### Descromprimir el archivo

In [26]:
from zipfile import ZipFile

In [27]:
pokemon_zip = ZipFile("pokemon_dataset.zip")

In [28]:
pokemon_zip.filelist

In [29]:
archivo = pokemon_zip.open("pokedex_mastermind.csv")

### Construir un data frame

In [30]:
import pandas as pd

In [31]:
df = pd.read_csv(archivo, index_col = [0]) #Recordemos siempre modificar la columna inicial

In [32]:
df.head()

,pokedex_number,name,generation,status,type_1,type_2,height_m,weight_pounds,hp,attack,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,1,Bulbasaur,1,Normal,GRASS,Poison,0.7,15.211878,45,49,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
1,2,Ivysaur,1,Normal,GRASS,Poison,1.0,28.660060,60,62,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
2,3,Venusaur,1,Normal,GRASS,Poison,2.0,220.462000,80,82,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
3,3,VenusaurMega Venusaur,1,Normal,GRASS,Poison,2.4,342.818410,80,100,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
4,4,Charmander,1,Normal,FIRE,NaN,0.6,18.739270,39,52,...,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5

In [33]:
df.tail()

,pokedex_number,name,generation,status,type_1,type_2,height_m,weight_pounds,hp,attack,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
1040,896,Glastrier,8,Sub Legendary,ICE,NaN,2.2,1763.696000,100,145,...,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0
1041,897,Spectrier,8,Sub Legendary,GHOST,NaN,2.0,98.105590,100,65,...,1.0,1.0,1.0,0.5,1.0,2.0,1.0,2.0,1.0,1.0
1042,898,Calyrex,8,Legendary,PSYCHIC,Grass,1.1,16.975574,100,80,...,0.5,2.0,0.5,4.0,1.0,2.0,1.0,2.0,1.0,1.0
1043,898,Calyrex Ice Rider,8,Legendary,PSYCHIC,Ice,2.4,1783.758042,100,165,...,1.0,1.0,0.5,2.0,2.0,2.0,1.0,2.0,2.0,1.0
1044,898,Calyrex Shadow Rider,8,Legendary,PSYCHIC,Ghost,2.4,118.167632,100,85,...,1.0,1.0,0.5,1.0,1.0,4.0,1.0,4.0,1.0,1.0

# Limpieza y Manipulación de datos

##  Quitar datos duplicados o irrelevantes

In [37]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1040    False
1041    False
1042    False
1043    False
1044    False
Length: 1045, dtype: bool

In [36]:
df.duplicated().any() #Esto nos trae False si nada es duplicado

False

In [39]:
#También podemos usar
df.duplicated().unique() #Este nos trae los valores unicos

array([False])

In [42]:
df.columns

Index(['pokedex_number', 'name', 'generation', 'status', 'type_1', 'type_2',
       'height_m', 'weight_pounds', 'hp', 'attack', 'defense', 'sp_attack',
       'sp_defense', 'speed', 'catch_rate', 'percentage_male',
       'against_normal', 'against_fire', 'against_water', 'against_electric',
       'against_grass', 'against_ice', 'against_fight', 'against_poison',
       'against_ground', 'against_flying', 'against_psychic', 'against_bug',
       'against_rock', 'against_ghost', 'against_dragon', 'against_dark',
       'against_steel', 'against_fairy'],
      dtype='object')

## Arreglar errores estructurales

In [43]:
df.head()

,pokedex_number,name,generation,status,type_1,type_2,height_m,weight_pounds,hp,attack,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,1,Bulbasaur,1,Normal,GRASS,Poison,0.7,15.211878,45,49,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
1,2,Ivysaur,1,Normal,GRASS,Poison,1.0,28.660060,60,62,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
2,3,Venusaur,1,Normal,GRASS,Poison,2.0,220.462000,80,82,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
3,3,VenusaurMega Venusaur,1,Normal,GRASS,Poison,2.4,342.818410,80,100,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
4,4,Charmander,1,Normal,FIRE,NaN,0.6,18.739270,39,52,...,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5

Como podemos observar, en el head no podemos varias columnas hay varios metodos para verlas todas, pero en este caso usaremos el siguiente metodo

In [45]:
df[['defense', 'sp_attack',
       'sp_defense', 'speed', 'catch_rate', 'percentage_male',
       'against_normal', 'against_fire', 'against_water', 'against_electric',
       'against_grass', 'against_ice', 'against_fight', 'against_poison']].head()

,defense,sp_attack,sp_defense,speed,catch_rate,percentage_male,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fight,against_poison
0,49,65,65,45,45.0,87.5%,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0
1,63,80,80,60,45.0,87.5%,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0
2,83,100,100,80,45.0,87.5%,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0
3,123,122,120,80,45.0,87.5%,1.0,1.0,0.5,0.5,0.25,1.0,0.5,1.0
4,43,60,50,65,45.0,87.5%,1.0,0.5,2.0,1.0,0.50,0.5,1.0,1.0

Lo que haremos, y que es el otro método, será traernos todos los weaknes a otro data frame para poder separarlo y tener mejor visualización

In [46]:
weakness = df[['against_normal', 'against_fire', 'against_water', 'against_electric',
       'against_grass', 'against_ice', 'against_fight', 'against_poison',
       'against_ground', 'against_flying', 'against_psychic', 'against_bug',
       'against_rock', 'against_ghost', 'against_dragon', 'against_dark',
       'against_steel', 'against_fairy']]

In [47]:
weakness.head()

,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fight,against_poison,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
1,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
2,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
3,1.0,1.0,0.5,0.5,0.25,1.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
4,1.0,0.5,2.0,1.0,0.50,0.5,1.0,1.0,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5

In [ ]:
#Lista de observaciones: 

#Mega venusaur tiene el nombre mal
#type_1 está en mayusculas
#peso tiene que estar en kilos
#percentage _male nos muestra un "%" ocupamos sea numerico o float

### Filtrar Outliers

### Lidiar con NANs

### Validad nuestros datos

# EDA

## ¿Cuál es el tipo de Pokémon más común?

## ¿Cuántos Pokémon legendarios hay en cada generación?

## ¿Su poder cambia generación tras generación?

## ¿Cuál es el tipo de Pokémon más poderoso?

## ¿Cuáles son los pokemon más grandes?, ¿más pesados? y ¿menos densos?

## ¿Cuántos Pokémon son machos y cuántos son hembra?

## ¿Qué pokemon tiene más ataque que defensa y viceversa?